"""Fraud typologies — real crimes, not random noise.

The governing rule (ADR 0004): fraud is a **transformation of honest claims**, never a
separate draw. `inject_fraud` takes the baseline population and mutates a small subset
of it. Nothing about a fraudulent claim differs from an honest one except the thing the
fraudster actually did.

Why that matters, concretely: if fraud were generated by its own sampler, it would
inherit a different RNG call order and therefore a slightly different amount
distribution — for reasons having nothing to do with the fraud. A LightGBM model would
find that difference in about thirty trees, report a PR-AUC of 0.97, and be measuring
your generator. Every synthetic fraud dataset that looks too good has this bug.

The five typologies below each map onto a specific feature family in §11, which is the
other half of the design: a typology nothing can detect is not a test, it is decoration.

Typology     -> what the fraudster does -> the feature family that should catch it

  DUPLICATE     resubmits a receipt weeks later, lightly edited
                -> duplicate signals: pHash distance, vendor+amount near-match
  SPLIT         breaks one large spend into legs under an approval limit
                -> velocity: n claims just under threshold in a short window
  INFLATION     pads mileage / per-diem by 15-30%
                -> employee-historical: z-score vs the employee's own category mean
  GHOST_VENDOR  invoices a vendor with no history, for a round amount
                -> vendor: first-seen recency, round-number flag
  COLLUSION     a manager waves through a report's padded claims
                -> peer-relative + the approval graph
  PERSONAL      weekend personal spend filed as a client dinner
                -> claim-intrinsic: weekend flag, attendee count
"""

from __future__ import annotations

from dataclasses import replace
from datetime import date, timedelta

import numpy as np

from fsa_sim.world.config import FraudConfig
from fsa_sim.world.entities import (
    Category,
    ExpenseRecord,
    FraudLabel,
    FraudTypology,
    User,
    Vendor,
)
from fsa_sim.world.spend import receipt_phash, submission_timestamp, synthesise_receipt_text

# Categories where padding an amount is plausible and hard to disprove.
_INFLATABLE = (Category.MILEAGE, Category.MEALS, Category.TRAVEL_GROUND, Category.LODGING)


def _resolve_clean(submitted: date, rng: np.random.Generator) -> date:
    """When a claim is recorded as clean.

    That is simply the reimbursement decision: a few days, not weeks. Every claim gets
    one — the business has to pay or not pay long before any auditor looks at it.
    """
    return submitted + timedelta(days=int(rng.integers(2, 11)))


def _resolve_fraud(
    submitted: date, config: FraudConfig, rng: np.random.Generator
) -> tuple[date, bool]:
    """When a fraudulent claim is resolved, and whether the audit actually caught it.

    Returns `(resolution_date, caught)`. A caught claim resolves after a lognormal
    audit lag around three weeks. A missed one resolves on the ordinary reimbursement
    timeline and is recorded **clean** — which is how undetected fraud ends up in the
    training data as a negative.

    That is not a flaw in the simulator. It is the single most important thing about
    fraud labels in production, and a dataset without it teaches a model that does not
    survive contact with reality.
    """
    if rng.random() > config.audit_coverage:
        return _resolve_clean(submitted, rng), False
    lag = rng.lognormal(
        mean=float(np.log(config.audit_lag_days_median)), sigma=config.audit_lag_days_sigma
    )
    return submitted + timedelta(days=int(min(lag, 400))), True


# ── the typologies ─────────────────────────────────────────────────────


def _duplicate(
    claim: ExpenseRecord, seq: int, rng: np.random.Generator
) -> tuple[list[ExpenseRecord], tuple[str, ...]]:
    """Resubmit the same receipt 30-90 days later, lightly altered.

    The alteration is the interesting part: the amount moves by a percent or two and
    the date shifts, so an exact-match check misses it. The perceptual hash barely
    changes, because the *image* is the same one — which is exactly why pHash distance
    rather than equality is the feature that catches this.
    """
    gap = int(rng.integers(30, 91))
    jitter = 1.0 + float(rng.normal(0, 0.015))
    amount = max(1, int(claim.amount_minor * jitter))
    txn = claim.transaction_date + timedelta(days=gap)
    copy = replace(
        claim,
        expense_id=f"{claim.tenant_id}-exp-f{seq:07d}",
        amount_minor=amount,
        transaction_date=txn,
        submitted_at=submission_timestamp(txn + timedelta(days=int(rng.integers(1, 8))), rng),
        # Same salt as the original => near-identical digest. That is the whole point.
        receipt_phash=claim.receipt_phash,
    )
    return [copy], (claim.expense_id,)


def _split(
    claim: ExpenseRecord, seq: int, config: FraudConfig, rng: np.random.Generator
) -> tuple[list[ExpenseRecord], tuple[str, ...]]:
    """Break one genuinely large spend into legs that each sit under the approval limit.

    The legs **sum to the original claim**, and this function is only ever handed a
    claim already above the threshold. Both constraints matter more than they look —
    see the note on candidate pools in `inject_fraud`. A splitter has a large real
    expense and wants it approved without a second signature; they do not conjure
    ₹29,000 out of a ₹380 taxi ride.

    Legs land within a few days of each other and share a vendor. Neither fact is
    suspicious alone; the *conjunction*, inside a trailing window, is. This is the
    typology only a velocity feature can see.
    """
    ceiling = config.approval_threshold_minor
    # Enough legs that each one clears the limit with a little headroom.
    n_legs = max(2, -(-claim.amount_minor // int(ceiling * 0.92)))
    weights = [int(w) for w in rng.integers(80, 121, size=n_legs)]
    total_weight = sum(weights)

    legs: list[ExpenseRecord] = []
    remaining = claim.amount_minor
    for i in range(n_legs):
        amount = (
            remaining
            if i == n_legs - 1
            else min(int(claim.amount_minor * weights[i] / total_weight), ceiling - 1)
        )
        amount = max(1, min(amount, ceiling - 1))
        remaining -= amount
        txn = claim.transaction_date + timedelta(days=int(rng.integers(0, 4)))
        legs.append(
            replace(
                claim,
                expense_id=f"{claim.tenant_id}-exp-f{seq + i:07d}",
                amount_minor=amount,
                transaction_date=txn,
                submitted_at=submission_timestamp(
                    txn + timedelta(days=int(rng.integers(0, 5))), rng
                ),
                receipt_phash=receipt_phash(claim.vendor_id, amount, txn, salt=f"split{i}"),
            )
        )
    return legs, tuple(leg.expense_id for leg in legs)


def _inflate(claim: ExpenseRecord, rng: np.random.Generator) -> list[ExpenseRecord]:
    """Pad the amount 15-30% and leave everything else alone.

    Deliberately subtle: there is no way to detect this from the claim itself. Only
    the employee's own history gives it away, which is what makes it the typology that
    justifies the whole point-in-time feature layer.
    """
    factor = 1.0 + float(rng.uniform(0.15, 0.30))
    amount = max(1, int(claim.amount_minor * factor))
    return [
        replace(
            claim,
            amount_minor=amount,
            receipt_ocr_text=claim.receipt_ocr_text,  # receipt unchanged: it is a lie
            receipt_phash=claim.receipt_phash,
        )
    ]


def _ghost_vendor(
    claim: ExpenseRecord, vendor: Vendor, rng: np.random.Generator
) -> list[ExpenseRecord]:
    """Invoice from a vendor with no history, for a suspiciously round amount.

    The amount is 2-6x the claim it replaces and then snapped to a round figure. It is
    scaled *relative to the original* rather than drawn from a fixed range, so a ghost
    invoice in office supplies is large-for-office-supplies rather than uniformly
    ₹20,000 — which would let the model detect this typology from `amount` alone,
    without ever learning that the vendor has no history.
    """
    inflated = claim.amount_minor * float(rng.uniform(2.0, 6.0))
    grid = 100_000 if inflated > 500_000 else 10_000  # round to ₹1,000 or ₹100
    amount = max(grid, int(round(inflated / grid) * grid))
    return [
        replace(
            claim,
            vendor_id=vendor.vendor_id,
            amount_minor=amount,
            description=f"consulting services - {vendor.name}",
            receipt_ocr_text=synthesise_receipt_text(
                vendor, amount, claim.transaction_date, claim.currency
            ),
            receipt_phash=receipt_phash(vendor.vendor_id, amount, claim.transaction_date),
        )
    ]


def _personal(claim: ExpenseRecord, rng: np.random.Generator) -> list[ExpenseRecord]:
    """Weekend personal spend refiled as a client dinner, attendees invented."""
    txn = claim.transaction_date
    shift = (5 - txn.weekday()) % 7  # nudge onto the following Saturday
    txn = txn + timedelta(days=shift or 7)
    amount = max(1, int(claim.amount_minor * float(rng.uniform(1.1, 2.0))))
    return [
        replace(
            claim,
            category=Category.CLIENT_ENTERTAINMENT,
            amount_minor=amount,
            transaction_date=txn,
            submitted_at=submission_timestamp(txn + timedelta(days=int(rng.integers(1, 10))), rng),
            attendee_count=int(rng.integers(2, 5)),  # claimed, not real
            description="client dinner",
        )
    ]


def _clean_label(claim: ExpenseRecord, rng: np.random.Generator) -> FraudLabel:
    """Label for a claim that is, and is recorded as, legitimate."""
    return FraudLabel(
        expense_id=claim.expense_id,
        is_fraud=False,
        typology=None,
        confirmed_at=submission_timestamp(_resolve_clean(claim.submitted_at.date(), rng), rng),
        observed_is_fraud=False,
    )


# ── orchestration ──────────────────────────────────────────────────────


def inject_fraud(
    expenses: list[ExpenseRecord],
    users: list[User],
    config: FraudConfig,
    rng: np.random.Generator,
    *,
    world_start: date,
) -> tuple[list[ExpenseRecord], list[Vendor], list[FraudLabel]]:
    """Transform a subset of honest claims into fraud.

    Returns the full expense list (honest + fraudulent), any ghost vendors that had to
    be created, and one `FraudLabel` per claim — including the honest ones, labelled
    `is_fraud=False`. Labelling everything rather than only the positives is what lets
    the ML layer do an honest join without inferring absence.

    A colluding manager is modelled by *concentrating* inflation on one employee whose
    manager is fixed for the run, rather than scattering it — collusion is a pattern in
    the approval graph, and a scattered version of it is just inflation with extra
    steps.
    """
    if not expenses:
        return [], [], []

    typologies = list(config.typology_mix)
    probs = np.array([config.typology_mix[t] for t in typologies], dtype=float)
    probs = probs / probs.sum()

    # One colluding pair per tenant, chosen up front so the pattern is concentrated in
    # the approval graph rather than smeared across the population.
    employees = [u for u in users if u.role == "employee" and u.manager_id]
    colluder = employees[int(rng.integers(len(employees)))] if employees else None

    # ── candidate pools ─────────────────────────────────────────────────────
    # Two typologies are only *possible* for certain claims, and drawing targets
    # uniformly then forcing the typology onto whatever came up is how a generator
    # invents a signal that has nothing to do with the crime. Concretely: splitting a
    # ₹380 taxi ride into three ₹29,000 legs made `amount ~= 26,000` a perfect
    # predictor of fraud in categories whose honest median is ₹377 — the model would
    # have learned the generator, exactly as ADR 0004 predicts.
    #
    # So each typology draws from the population where it makes sense:
    #   SPLIT     -> claims already above the approval threshold
    #   COLLUSION -> the colluding employee's own claims
    # and degrades to INFLATION when its pool is empty.
    splittable = [
        i for i, e in enumerate(expenses) if e.amount_minor > config.approval_threshold_minor
    ]
    colluder_claims = (
        [i for i, e in enumerate(expenses) if e.user_id == colluder.user_id] if colluder else []
    )

    n_targets = int(len(expenses) * config.base_rate)
    plan: dict[int, FraudTypology] = {}
    generic_pool = list(range(len(expenses)))
    rng.shuffle(generic_pool)
    pools: dict[FraudTypology, list[int]] = {
        FraudTypology.SPLIT: list(splittable),
        FraudTypology.COLLUSION: list(colluder_claims),
    }
    for typology in pools:
        rng.shuffle(pools[typology])

    cursor = 0
    for _ in range(min(n_targets, len(expenses))):
        typology = typologies[int(rng.choice(len(typologies), p=probs))]
        pool = pools.get(typology)
        if pool is not None:
            while pool and pool[-1] in plan:
                pool.pop()
            if not pool:
                typology = FraudTypology.INFLATION
            else:
                plan[pool.pop()] = typology
                continue
        while cursor < len(generic_pool) and generic_pool[cursor] in plan:
            cursor += 1
        if cursor >= len(generic_pool):
            break
        plan[generic_pool[cursor]] = typology
        cursor += 1

    kept: list[ExpenseRecord] = []
    labels: list[FraudLabel] = []
    ghost_vendors: list[Vendor] = []
    seq = 0

    for index, claim in enumerate(expenses):
        planned = plan.get(index)
        if planned is None:
            kept.append(claim)
            labels.append(_clean_label(claim, rng))
            continue

        seq += 10
        linked: tuple[str, ...] = ()

        if planned is FraudTypology.DUPLICATE:
            kept.append(claim)  # the original submission is legitimate
            labels.append(_clean_label(claim, rng))
            produced, linked = _duplicate(claim, seq, rng)
        elif planned is FraudTypology.SPLIT:
            produced, linked = _split(claim, seq, config, rng)
        elif planned is FraudTypology.GHOST_VENDOR:
            ghost = Vendor(
                vendor_id=f"{claim.tenant_id}-v-ghost{seq:05d}",
                tenant_id=claim.tenant_id,
                name=f"Meridian Consulting {seq}",
                category=claim.category,
                # First seen days before the claim: no history to check against.
                first_seen_on=max(world_start, claim.transaction_date - timedelta(days=9)),
            )
            ghost_vendors.append(ghost)
            produced = _ghost_vendor(claim, ghost, rng)
        elif planned is FraudTypology.PERSONAL:
            produced = _personal(claim, rng)
        else:  # INFLATION, and COLLUSION on the colluder's own claims
            produced = _inflate(claim, rng)
            if planned is FraudTypology.COLLUSION and colluder is not None:
                # The approving manager is the second party. Recorded on the label so
                # the peer-relative / approval-graph features have something to find.
                linked = (str(colluder.manager_id),)

        for record in produced:
            kept.append(record)
            resolved, caught = _resolve_fraud(record.submitted_at.date(), config, rng)
            labels.append(
                FraudLabel(
                    expense_id=record.expense_id,
                    is_fraud=True,  # what actually happened
                    typology=planned,
                    confirmed_at=submission_timestamp(resolved, rng),
                    observed_is_fraud=caught,  # what the business recorded
                    linked_expense_ids=linked,
                )
            )

    return kept, ghost_vendors, labels
